services:
  postgres:
    image: postgres:latest
    container_name: postgres_literalura
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_literalura:/var/lib/postgresql/data

volumes:
  postgres_data_literalura: