spring:
  application:
    name: literalura

  datasource:
    url: jdbc:postgresql://localhost:5432/db-literalura
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true